[pytest]
base_url = url
addopts = --alluredir=allure-results --junitxml=reportes/junit-results.xml
pythonpath = .
testpaths = tests
norecursedirs = .git __pycache__ .pytest_cache allure-results allure-reports reportes .venv
markers =
    smoke: Pruebas criticas de disponibilidad y acceso
    login: Pruebas de autenticacion
    login_negativo: Pruebas negativas de autenticacion
    guia_madre: Pruebas de creacion de guias madre
    guia_madre_negativo: Pruebas negativas de guias madre
    entrega_aduana: Pruebas de entrega de guias madre a aduana
    agregar_consolidado: Pruebas de carga de consolidados en guias madre
    despacho_cajas: Pruebas de despacho de cajas de consolidados
    control_aduanero: Flujos del proyecto Control Aduanero FD
